### ISSUE TITLE
Findbugs doesn't work on Windows

### ISSUE THREAD

**Issue by etyurkin** [josephearl/sbt-findbugs#10]
There're two problems:
1. Windows uses back slash as path separator which is disappears when plugin builds class path command line argument. Back slashes needed to be converted to forward slashes.
2. Windows eats empty space from arguments, this is a problem for -pluginList argument when no plugins defined. -pluginList should be removed from command line if there's no findbugs plugins defined.

Attached patch fixes both issues and was tested on OSX and Windows.
[001-make-findbugs-work-on-Windows.txt](https://github.com/JosephEarl/sbt-findbugs/files/372678/001-make-findbugs-work-on-Windows.txt)

**Comment by josephearl** [comment]
Thanks for the patch @etyurkin! Keep them coming :wink: I will take a look and review it this evening. 

Will look into getting the CI build on Travis to run the tests on Windows so these issues can be caught sooner.

**Comment by josephearl** [comment]
Looks like Travis still doesn't support Windows - so looking into [AppVeyor](http://www.appveyor.com) for the Windows CI builds. Just testing the build out now with the patch applied https://github.com/JosephEarl/sbt-findbugs/tree/windows-support.

Travis does support both OS X & Linux though, so would be worth using it to test both of those OSes instead of just the one.

**Comment by etyurkin** [comment]
It should work on OS X as long as it works on any other unixes, so Linux test should be enough

**Comment by josephearl** [comment]
I've applied this patch and added a Windows CI build using AppVeyor and pushed a new build to Bintray as 2.4.3 :ship:

Thanks again for this! 💯 

PS I had to make one change to the patch:

``` scala
case plugins => arguments ++ List("-pluginList", plugins mkString ":")
```

instead of:

``` scala
case Seq(plugins) => arguments ++ List("-pluginList", plugins mkString ":")
```

**Comment by etyurkin** [comment]
Thanks! Now I can force everyone to use findbugs (evil)
