### ISSUE TITLE
Update README.md to include FindBugsReportType.XmlWithMessages

### ISSUE THREAD

**Issue by etyurkin** [josephearl/sbt-findbugs#11]
Plugin now supports XmlWithMessages report type and README.md was updated accordingly.
However XSLT transformations section (https://github.com/JosephEarl/sbt-findbugs#xslt-transformations) was not updated, it says:

"This setting is only compatible with findbugsReportType := Some(FindBugsReportType.Xml) (the default)."

Should be 

"This setting is only compatible with findbugsReportType := Some(FindBugsReportType.Xml) (the default) or Some(FindBugsReportType.XmlWithMessages)"

**Comment by josephearl** [comment]
Thanks missed that!

**Comment by josephearl** [comment]
Closed by f6a0490
