### ISSUE TITLE
HTML Report file generation not working

### ISSUE THREAD

**Issue by jon-strayer** [josephearl/sbt-findbugs#12]
Or at least I don't understand how it is supposed to  work.

Adding this line to build.sbt

`findbugsReportType := Some(FindBugsReportType.FancyHtml)`

gets me an xml report but no HTML report.

**Comment by josephearl** [comment]
It will still generate a file named `.xml` unless you have changed the file name with `findbugsReportPath`, but it should in fact contain HTML.

What you probably want to do is both set the type to `FancyHtml` **and** change the file name it uses for the report, e.g.:

``` scala
findbugsReportType := Some(FindBugsReportType.FancyHtml)
findbugsReportPath := Some(target.value / "findbugs-report.xml")
```

**Comment by jon-strayer** [comment]
That is correct.

**Comment by josephearl** [comment]
Feel free to open an issue or PR to make the default report name depend on the report type, since this behaviour is a bit unintuitive
