### ISSUE TITLE
I can't get findbugsExcludeFilters to work (including an xml file)

### ISSUE THREAD

**Issue by jon-strayer** [josephearl/sbt-findbugs#14]
This line in build.sbt:
`findbugsExcludeFilters := Some(baseDirectory.value / "findbugs-exclude-filters.xml")`

Leads to this error message:

```
error: type mismatch;
 found   : java.io.File
 required: scala.xml.Node
findbugsExcludeFilters := Some(baseDirectory.value / "findbugs-exclude-filters.xml")
                                                   ^
```

**Comment by josephearl** [comment]
Hi @jon-strayer, sbt-findbugs doesn't currently support loading XML files.

You can either supply XML inline, or you should be able to load the file yourself:

``` scala
findbugsExcludeFilters := Some(scala.xml.XML.loadFile(baseDirectory.value / "findbugs-exclude-filters.xml"))
```

If that works for you let me know and will add it to the README as an example

**Comment by josephearl** [comment]
Have updated the docs to inform users they need to use `scala.xml.XML.loadFile` or similar.
