### ISSUE TITLE
Configuration for ITA_INEFFICIENT_TO_ARRAY and Experimental

### ISSUE THREAD

**Issue by youngki924** [josephearl/sbt-findbugs#15]
Hello,

Is it possible to configure the following?
1. Enable a detector, ITA_INEFFICIENT_TO_ARRAY
2. Disable "Experimental" from Reporting

Thank you,
Youngki

**Comment by josephearl** [comment]
Where does the detector `ITA_INEFFICIENT_TO_ARRAY` come from? Is part of a plugin?

Experimental reporting should be disabled by default. You can exclude experimental reporting by setting `findBugsPriority` to something higher than `FindBugsPriority.Relaxed` (it should be `FindBugsPriority.Medium` by default).

Alternatively you can exclude experimental reporting for some or all classes using `findbugsExcludeFilters`:

```
findbugsExcludeFilters := Some(<FindBugsFilter>
  <Match>
    <Bug category="EXPERIMENTAL" />
  </Match>
</FindBugsFilter>)
```

Edit: It looks like the EXPERIMENTAL category is enabled by default, and setting `findbugsPriority` does not exclude it. Use `findbugsExcludeFilters` instead.

**Comment by josephearl** [comment]
It looks like the `ITA_INEFFICIENT_TO_ARRAY` is part of FindBugs, but is not enabled by default because it is no longer valid - see https://github.com/findbugsproject/findbugs/issues/78, in fact the opposite is now true.

**Comment by josephearl** [comment]
It doesn't look like you can use `findbugsIncludeFilters` to enable disabled detectors.

I've asked on the FindBugs project how you can enable this https://github.com/findbugsproject/findbugs/issues/145.

**Comment by JosephEarl** [comment]
It looks like the EXPERIMENTAL category is enabled by default, and setting findbugsPriority does not seem to exclude it, but using `findbugsExcludeFilters` to ignore that category does work.

**Comment by youngki924** [comment]
Thanks, Joe.

I tried to enable ITA_INEFFICIENT_TO_ARRAY as below but not sure whether it is working.

```
findbugsIncludeFilters := Some(<FindBugsFilter>
  <Match>
    <Bug pattern="ITA_INEFFICIENT_TO_ARRAY"/>
  </Match>
</FindBugsFilter>)
```

For EXPERIMENTAL, I will try findbugsExcludeFilters as your suggestion.

Thanks,
Youngki
