### ISSUE TITLE
Add XmlWithMessages report type

### ISSUE THREAD

**Issue by etyurkin** [josephearl/sbt-findbugs#9]
Findbugs supports xml report with messages via -xml:withMessages command line switch.
With attached patch applied I can use plugin with 

findbugsFailOnError := true 
findbugsReportType := Some(FindBugsReportType.XmlWithMessages)
findbugsXsltTransformations := Some(Set(FindBugsXSLTTransformation(baseDirectory(_ / "findbugs" / "fancy.xsl").value, target(_ / "findbugs/report.html").value)))

to generate meaningful reports and fail build at the same time.
[001-add-FindBugsReportType.XmlWithMessages.txt](https://github.com/JosephEarl/sbt-findbugs/files/370017/001-add-FindBugsReportType.XmlWithMessages.txt)

**Comment by josephearl** [comment]
Thanks @etyurkin, will merge this shortly and update the docs.

**Comment by josephearl** [comment]
Updated and published 2.4.2 with the XmlWithMessages report type. Thanks for your contribution! I have added your GitHub name to the [CONTRIBUTING.md](https://github.com/JosephEarl/sbt-findbugs/blob/master/CONTRIBUTING.md).
